spring:
  config:
    activate:
      on-profile: security-prod
app:
  jwt:
    secret: ${JWT_SECRET}
    bearer-type: ${JWT_BEARER_TYPE}
    auth-header: ${JWT_AUTH_HEADER}
    expiration:
      access: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
      refresh: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

logging:
  level:
    org.springframework.security: WARN
