spring:
  config:
    activate:
      on-profile: security-local
app:
  jwt:
    secret: iy9mezMgQvVfRMPACkVtsnftFnrUK8pn
    bearer-type: Bearer
    auth-header: Authorization
    expiration:
      access: 60 # 60  (1 minute)
      refresh: 300 # 60 * 5 (5 minute)

logging:
  level:
    org.springframework.security: DEBUG
