name: Build & Push Docker Image on PR to prod

on:
  pull_request:
    branches: [ "prod" ]

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and Test (Gradle)
        run: |
          gradle clean build -x test
          gradle test

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image with 'latest' Tag
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/fall-prevention"
          IMAGE_TAG="latest"

          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
          docker push $IMAGE_NAME:$IMAGE_TAG
