name: Sync Prod to Main

on:
  push:
    branches:
      - prod

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge Prod into Main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout main
          git merge --ff-only prod
          git push origin main
